language: node_js
node_js:
  - "6.9"

cache:
  directories:
    - $(npm config get prefix)/bin
    - node_modules

branches:
  only:
    - master

before_script:
  - ng || npm install -g @angular/cli

script:
  - ng build --prod -bh https://nss-alumni.github.io/hackathon1-team12/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master

